/**
 * MAISON VERNIS - PRODUCT CATALOGUE
 * 50 Unique Luxury Fashion & Accessory Items
 */

const PRODUCTS = [

  // MEN'S CLOTHING & OUTERWEAR (1 - 10)
  {
    id: "mv-m-01",
    name: "Double-Breasted Cashmere Overcoat",
    category: "Coats",
    gender: "Men",
    price: 3450,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Tailored in Italy from pure Mongolian cashmere with horn buttons and silk lining.",
    description: "An iconic silhouette crafted for timeless warmth. Featuring hand-stitched lapels, structural shoulders, interior welt pockets, and a subtle rear vent.",
    rating: 4.9,
    reviewsCount: 28,
    sizes: ["46", "48", "50", "52", "54"],
    colors: ["Camel", "Noir", "Navy"],
    badge: "New Arrival",
    isFeatured: true,
    isBestSeller: true
  },
  {
    id: "mv-m-02",
    name: "Structured Wool Blazer",
    category: "Jackets",
    gender: "Men",
    price: 1890,
    salePrice: 1512,
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Single-breasted architectural blazer cut from structured virgin wool.",
    description: "A refined foundation for modern tailoring. Features notch lapels, genuine mother-of-pearl buttons, and cupro full lining.",
    rating: 4.8,
    reviewsCount: 19,
    sizes: ["46", "48", "50", "52"],
    colors: ["Charcoal", "Midnight Blue"],
    badge: "Sale",
    isFeatured: true,
    isBestSeller: false
  },
  {
    id: "mv-m-03",
    name: "Poplin Pleated Tuxedo Shirt",
    category: "Shirts",
    gender: "Men",
    price: 680,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Woven 180s Egyptian cotton shirt with hand-pleated bib.",
    description: "Designed for black-tie elegance. Cut with french cuffs, concealed button placket, and stiff spread collar.",
    rating: 4.7,
    reviewsCount: 14,
    sizes: ["38", "39", "40", "41", "42"],
    colors: ["Crisp White"],
    badge: null,
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-m-04",
    name: "Heavyweight Organic Cotton T-Shirt",
    category: "T-shirts",
    gender: "Men",
    price: 290,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80",
    shortDescription: "280gsm organic jersey knit with drop shoulder and ribbed collar.",
    description: "Elevated everyday essential crafted in Portugal. Mercerized finish delivers a silky feel and color depth.",
    rating: 4.6,
    reviewsCount: 42,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Chalk", "Olive"],
    badge: "Essential",
    isFeatured: false,
    isBestSeller: true
  },
  {
    id: "mv-m-05",
    name: "Tailored Tapered Trousers",
    category: "Trousers",
    gender: "Men",
    price: 790,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1479064555552-3ef4979f8908?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Fluid wool-gabardine trousers with side adjusters and double front pleats.",
    description: "Designed with a high rise and sharp leg crease. Ideal for pairing with relaxed knitwear or formal tailoring.",
    rating: 4.8,
    reviewsCount: 22,
    sizes: ["46", "48", "50", "52"],
    colors: ["Taupe", "Noir"],
    badge: null,
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-m-06",
    name: "Raw Japanese Denim Jeans",
    category: "Jeans",
    gender: "Men",
    price: 480,
    salePrice: null,
 image: "https://images.unsplash.com/photo-1590324099257-2a4acb01b0b1?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80",
    shortDescription: "15oz Kurabo selvedge denim, unwashed with hidden rivets.",
    description: "Crafted in Okayama. Straight-leg cut designed to age gracefully over time, taking on unique wear patterns.",
    rating: 4.9,
    reviewsCount: 31,
    sizes: ["30", "31", "32", "33", "34", "36"],
    colors: ["Indigo Selvedge"],
    badge: "Iconic",
    isFeatured: true,
    isBestSeller: true
  },
  {
    id: "mv-m-07",
    name: "Nappa Leather Biker Jacket",
    category: "Jackets",
    gender: "Men",
    price: 2850,
    salePrice: 2280,
    image: "https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Supple lambskin leather with palladium hardware and asymmetric zip.",
    description: "An enduring piece featuring hand-buffed seams, quilted shoulder panels, and multiple zip pockets.",
    rating: 4.9,
    reviewsCount: 16,
    sizes: ["48", "50", "52", "54"],
    colors: ["Matte Black"],
    badge: "Sale",
    isFeatured: true,
    isBestSeller: false
  },
  {
    id: "mv-m-08",
    name: "Chunky Gauge Cashmere Turtleneck",
    category: "Shirts",
    gender: "Men",
    price: 920,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1610652492500-ded49ceeb378?auto=format&fit=crop&w=800&q=80",
    shortDescription: "7-gauge 2-ply cashmere knit with ribbed cuffs and foldover neck.",
    description: "Unmatched thermal insulation and soft touch. Spun in Scotland using pristine spring waters.",
    rating: 4.8,
    reviewsCount: 11,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Oatmeal", "Charcoal", "Ivory"],
    badge: "Winter Warmth",
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-m-09",
    name: "Silk-Blend Short Sleeve Resort Shirt",
    category: "Shirts",
    gender: "Men",
    price: 520,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Camp collar shirt woven from 70% silk and 30% breathable linen.",
    description: "Fluid silhouette printed with subtle geometric tonal Jacquard weave. Finished with mother-of-pearl buttons.",
    rating: 4.7,
    reviewsCount: 18,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Sand", "Emerald Tonal"],
    badge: null,
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-m-10",
    name: "Technical Trench Coat with Belt",
    category: "Coats",
    gender: "Men",
    price: 2100,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Water-repellent gabardine trench with leather buckle closures.",
    description: "Modern reinterpretation of military outerwear. Double-breasted with epaulettes, rain shield, and storm flap.",
    rating: 4.9,
    reviewsCount: 15,
    sizes: ["46", "48", "50", "52", "54"],
    colors: ["Honey", "Black"],
    badge: "New Arrival",
    isFeatured: false,
    isBestSeller: false
  },

  // WOMEN'S CLOTHING & DRESSES (11 - 22)
  {
    id: "mv-w-01",
    name: "Asymmetric Silk Gown",
    category: "Dresses",
    gender: "Women",
    price: 2950,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Heavy silk crepe de chine gown featuring sculptural draped neckline.",
    description: "Masterful draping creates a statuesque silhouette. Side slit, concealed back zipper, and floor-length fluid drop.",
    rating: 5.0,
    reviewsCount: 34,
    sizes: ["36", "38", "40", "42"],
    colors: ["Noir", "Emerald", "Scarlet"],
    badge: "Editorial Choice",
    isFeatured: true,
    isBestSeller: true
  },
  {
    id: "mv-w-02",
    name: "Belted Cashmere Wrap Coat",
    category: "Coats",
    gender: "Women",
    price: 3800,
    salePrice: 3040,
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Double-faced cashmere long coat with generous shawl collar.",
    description: "Hand-finished edges and unlined construction give an effortless light drape while retaining high thermal comfort.",
    rating: 4.9,
    reviewsCount: 27,
    sizes: ["36", "38", "40", "42"],
    colors: ["Oatmeal", "Black"],
    badge: "Sale",
    isFeatured: true,
    isBestSeller: true
  },
  {
    id: "mv-w-03",
    name: "Sculptural Satin Midi Dress",
    category: "Dresses",
    gender: "Women",
    price: 1650,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Duchesse satin midi dress with corseted bodice and flared skirt.",
    description: "Crafted to accentuate the waistline. Internal boning structure provides structure without compromising grace.",
    rating: 4.8,
    reviewsCount: 20,
    sizes: ["34", "36", "38", "40"],
    colors: ["Champagne", "Midnight"],
    badge: "New Arrival",
    isFeatured: true,
    isBestSeller: false
  },
  {
    id: "mv-w-04",
    name: "Oversized Shearling Jacket",
    category: "Jackets",
    gender: "Women",
    price: 3200,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1520591799316-6b30425429aa?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Plongé leather shearling jacket with plush shearling lining.",
    description: "Warmth meets high-fashion volume. Buckled collar straps, oversized zip hardware, and plush turn-up cuffs.",
    rating: 4.9,
    reviewsCount: 12,
    sizes: ["36", "38", "40"],
    colors: ["Cognac/Cream", "All-Black"],
    badge: null,
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-w-05",
    name: "Silk Satin Tailored Blouse",
    category: "Shirts",
    gender: "Women",
    price: 590,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1584273143981-41c073dfe8f8?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Pure mulberry silk shirt with exaggerated cuff details.",
    description: "Fluid silhouette that transitions seamlessly from executive wear to evening cocktails. Concealed front placket.",
    rating: 4.7,
    reviewsCount: 31,
    sizes: ["34", "36", "38", "40", "42"],
    colors: ["Ivory", "Earthy Taupe"],
    badge: "Essential",
    isFeatured: false,
    isBestSeller: true
  },
  {
    id: "mv-w-06",
    name: "High-Rise Wide-Leg Trousers",
    category: "Trousers",
    gender: "Women",
    price: 740,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Fluid wool crepe trousers cut with dramatic leg width.",
    description: "Elongating fit designed with high waist band, front pleats, and side slip pockets. Timeless tailoring.",
    rating: 4.8,
    reviewsCount: 25,
    sizes: ["34", "36", "38", "40"],
    colors: ["Off-White", "Black"],
    badge: null,
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-w-07",
    name: "Pleated Organza Cocktail Dress",
    category: "Dresses",
    gender: "Women",
    price: 1850,
    salePrice: 1480,
    image: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Sunray pleated silk organza dress with tiered hem.",
    description: "Lightweight architectural movement. Translucent long sleeves and delicate keyhole button back closure.",
    rating: 4.6,
    reviewsCount: 16,
    sizes: ["36", "38", "40"],
    colors: ["Blush Pink", "Dusty Blue"],
    badge: "Sale",
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-w-08",
    name: "Fine Knit Cashmere Cardigan",
    category: "Shirts",
    gender: "Women",
    price: 680,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Ultra-fine gauge cashmere button-down knit with mother-of-pearl hardware.",
    description: "Featherlight warmth suitable for elevated layering. Ribbed trim accents at cuff and hemline.",
    rating: 4.9,
    reviewsCount: 38,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Cream", "Camel", "Soft Sage"],
    badge: "Best Seller",
    isFeatured: false,
    isBestSeller: true
  },
  {
    id: "mv-w-09",
    name: "High-Waisted Straight Denim",
    category: "Jeans",
    gender: "Women",
    price: 420,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1542272604-780c36856d62?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Organic Italian cotton denim with authentic vintage wash.",
    description: "Classic five-pocket styling with rigid structural support that shapes over time. An essential casual staple.",
    rating: 4.7,
    reviewsCount: 29,
    sizes: ["25", "26", "27", "28", "29", "30"],
    colors: ["Vintage Wash", "Raw Black"],
    badge: null,
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-w-10",
    name: "Ribbed Merino Knit T-Shirt",
    category: "T-shirts",
    gender: "Women",
    price: 310,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Extra-fine merino wool fitted T-shirt with seamless finish.",
    description: "Provides sleek layering under tailoring or structured jackets. Temperature regulating natural fibers.",
    rating: 4.5,
    reviewsCount: 17,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Nude", "Noir"],
    badge: null,
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-w-11",
    name: "Double-Breasted Velvet Blazer",
    category: "Jackets",
    gender: "Women",
    price: 1450,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1551803091-e20673f15770?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Cotton-velvet tuxedo jacket with satin peak lapels.",
    description: "Deep lush pile texture paired with sharp power shoulders. Perfect statement tailoring for evening galas.",
    rating: 4.8,
    reviewsCount: 15,
    sizes: ["36", "38", "40"],
    colors: ["Midnight Wine", "Deep Onyx"],
    badge: "Limited Edition",
    isFeatured: true,
    isBestSeller: false
  },
  {
    id: "mv-w-12",
    name: "Tiered Silk Slip Dress",
    category: "Dresses",
    gender: "Women",
    price: 980,
    salePrice: 784,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Bias-cut silk satin slip with adjustable French lace shoulder straps.",
    description: "Skims the body gracefully. Finished with hand-applied Chantilly lace along the hem line.",
    rating: 4.7,
    reviewsCount: 23,
    sizes: ["34", "36", "38", "40"],
    colors: ["Champagne", "Black"],
    badge: "Sale",
    isFeatured: false,
    isBestSeller: false
  },

  // FOOTWEAR / SHOES (23 - 32)
  {
    id: "mv-s-01",
    name: "Pointed Leather Stiletto Pumps",
    category: "Shoes",
    gender: "Women",
    price: 890,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?auto=format&fit=crop&w=800&q=80",
    shortDescription: "105mm heels in patent calfskin with cushioned footbed.",
    description: "Handcrafted in Florence. Features sleek architectural heels, signature golden lining, and leather soles.",
    rating: 4.9,
    reviewsCount: 41,
    sizes: ["36", "37", "38", "39", "40"],
    colors: ["Black Patent", "Nude"],
    badge: "Best Seller",
    isFeatured: true,
    isBestSeller: true
  },
  {
    id: "mv-s-02",
    name: "Handcrafted Leather Oxford Shoes",
    category: "Shoes",
    gender: "Men",
    price: 950,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Goodyear-welted full-grain calfskin Oxfords with hand patina.",
    description: "Built to last decades. Hand-burnished toe box, closed lacing, and double-stitched leather soles.",
    rating: 4.9,
    reviewsCount: 30,
    sizes: ["40", "41", "42", "43", "44", "45"],
    colors: ["Espresso", "Black"],
    badge: null,
    isFeatured: false,
    isBestSeller: true
  },
  {
    id: "mv-s-03",
    name: "Minimalist Leather Court Sneakers",
    category: "Shoes",
    gender: "Unisex",
    price: 520,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Italian Nappa leather low-top sneakers with rubber Margom sole.",
    description: "Monochromatic luxury casual footwear. Gold foil stamped serial numbers and calfskin interior lining.",
    rating: 4.8,
    reviewsCount: 56,
    sizes: ["37", "38", "39", "40", "41", "42", "43", "44"],
    colors: ["Optic White", "Off-White/Gry"],
    badge: "Iconic",
    isFeatured: true,
    isBestSeller: true
  },
  {
    id: "mv-s-04",
    name: "Knee-High Stretch Leather Boots",
    category: "Shoes",
    gender: "Women",
    price: 1420,
    salePrice: 1136,
    image: "https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Skin-tight stretch lambskin boots on a 75mm block heel.",
    description: "Seamless hugging profile with inner zip closure and anti-slip leather outsole. Modern elegance.",
    rating: 4.7,
    reviewsCount: 18,
    sizes: ["36", "37", "38", "39", "40"],
    colors: ["Black Lambskin"],
    badge: "Sale",
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-s-05",
    name: "Suede Chelsea Boots",
    category: "Shoes",
    gender: "Men",
    price: 820,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1638247025967-b4e38f787b76?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Water-resistant calf suede Chelsea boots with elastic gores.",
    description: "Sleek round toe profile crafted in Northamptonshire. Crepe-textured rubber welt sole for traction.",
    rating: 4.8,
    reviewsCount: 24,
    sizes: ["40", "41", "42", "43", "44"],
    colors: ["Chocolate Suede", "Sand Suede"],
    badge: null,
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-s-06",
    name: "Strappy Crystal Sandals",
    category: "Shoes",
    gender: "Women",
    price: 1100,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1562273138-f46be4ebdf33?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Satin ankle-wrap heels adorned with crystal-embellished straps.",
    description: "Designed for grand occasions. Stiletto heel measures 90mm with memory foam padded insoles.",
    rating: 4.9,
    reviewsCount: 15,
    sizes: ["36", "37", "38", "39"],
    colors: ["Silver Crystal", "Black Crystal"],
    badge: "New Arrival",
    isFeatured: true,
    isBestSeller: false
  },
  {
    id: "mv-s-07",
    name: "Grain Leather Penny Loafers",
    category: "Shoes",
    gender: "Men",
    price: 780,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Pebble grain calfskin loafers with hand-sewn apron detail.",
    description: "Unlined flexible construction delivering instant comfort without break-in time. Rubber heel tap.",
    rating: 4.6,
    reviewsCount: 19,
    sizes: ["41", "42", "43", "44", "45"],
    colors: ["Black Grain", "Cognac"],
    badge: null,
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-s-08",
    name: "Chunky Lug-Sole Combat Boots",
    category: "Shoes",
    gender: "Women",
    price: 990,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Polished Spazzalato leather boots with lightweight rubber platform.",
    description: "High-contrast urban style. Lace-up front backed by a inner zip mechanism for effortless fitting.",
    rating: 4.8,
    reviewsCount: 22,
    sizes: ["36", "37", "38", "39", "40"],
    colors: ["Gloss Black"],
    badge: null,
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-s-09",
    name: "Velvet Evening Slippers",
    category: "Shoes",
    gender: "Men",
    price: 650,
    salePrice: 520,
   image: "https://images.unsplash.com/photo-1568252542512-9fe8fe9c87bb?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Cotton velvet loafers embroidered with subtle gold thread cipher.",
    description: "Quilted satin footbed offering slipper-like comfort with formal footwear stature.",
    rating: 4.7,
    reviewsCount: 8,
    sizes: ["40", "41", "42", "43", "44"],
    colors: ["Burgundy", "Navy Velvet"],
    badge: "Sale",
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-s-10",
    name: "Suede Pointed Mules",
    category: "Shoes",
    gender: "Women",
    price: 620,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1560343090-f0409e92791a?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80",
    shortDescription: "50mm kitten heel mules in butter-soft kid suede.",
    description: "Sleek everyday slip-on design with extended pointy toe box and V-cut vamp.",
    rating: 4.6,
    reviewsCount: 14,
    sizes: ["36", "37", "38", "39", "40"],
    colors: ["Terracotta", "Olive Suede"],
    badge: null,
    isFeatured: false,
    isBestSeller: false
  },

  // HANDBAGS & LEATHER GOODS (33 - 41)
  {
    id: "mv-b-01",
    name: "Structured Calfskin Top-Handle Bag",
    category: "Bags",
    gender: "Women",
    price: 2800,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Architectural tote in box calfskin with signature gold turn-lock closure.",
    description: "Hand-painted edge finishing, interior zip compartment, detachable leather crossbody strap, and suede lining.",
    rating: 5.0,
    reviewsCount: 47,
    sizes: ["One Size"],
    colors: ["Noir", "Cognac", "Chalk White"],
    badge: "Iconic",
    isFeatured: true,
    isBestSeller: true
  },
  {
    id: "mv-b-02",
    name: "Quilted Lambskin Shoulder Bag",
    category: "Bags",
    gender: "Women",
    price: 3200,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Chevron-quilted leather bag with convertible sliding chain strap.",
    description: "Supple Nappa leather padded to perfection. Gold-tone monogram hardware and dual magnetic flap closure.",
    rating: 4.9,
    reviewsCount: 62,
    sizes: ["One Size"],
    colors: ["Black/Gold", "Ivory/Gold"],
    badge: "Best Seller",
    isFeatured: true,
    isBestSeller: true
  },
  {
    id: "mv-b-03",
    name: "Minimalist Leather Weekender Tote",
    category: "Bags",
    gender: "Unisex",
    price: 1950,
    salePrice: 1560,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Full-grain pebbled travel duffel with reinforced base metal feet.",
    description: "Generous interior capacity with padded laptop sleeve, passport pocket, and heavy-duty brass zip closures.",
    rating: 4.8,
    reviewsCount: 23,
    sizes: ["One Size"],
    colors: ["Espresso", "Black Grain"],
    badge: "Sale",
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-b-04",
    name: "Micro Leather Crossbody Pouch",
    category: "Bags",
    gender: "Women",
    price: 920,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Petite structured crossbody crafted for mobile phone and card storage.",
    description: "Features four internal card slots, slim leather strap, and polished gold clasp.",
    rating: 4.6,
    reviewsCount: 19,
    sizes: ["One Size"],
    colors: ["Burgundy", "Olive", "Mustard"],
    badge: "New Arrival",
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-b-05",
    name: "Grained Leather Briefcase",
    category: "Bags",
    gender: "Men",
    price: 2100,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Executive slim document case with dual top handles and trolley strap.",
    description: "Designed for the global professional. Holds a 15-inch laptop with dedicated organizer pockets.",
    rating: 4.9,
    reviewsCount: 21,
    sizes: ["One Size"],
    colors: ["Navy", "Dark Brown"],
    badge: null,
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-b-06",
    name: "Pleated Satin Clutch Bag",
    category: "Bags",
    gender: "Women",
    price: 780,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Evening frame clutch in folded silk satin with detachable chain.",
    description: "Sculptural clutch silhouette with crystal-encrusted clasp closure and silk lining.",
    rating: 4.7,
    reviewsCount: 16,
    sizes: ["One Size"],
    colors: ["Emerald", "Silver Satin"],
    badge: null,
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-b-07",
    name: "Soft Suede Bucket Bag",
    category: "Bags",
    gender: "Women",
    price: 1450,
    salePrice: 1160,
    image: "https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Slouchy bucket silhouette crafted in Italian calf suede with drawstring toggle.",
    description: "Relaxed luxury. Unlined raw interior with attached interior zip wristlet pouch.",
    rating: 4.6,
    reviewsCount: 13,
    sizes: ["One Size"],
    colors: ["Camel Suede", "Chocolate"],
    badge: "Sale",
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-b-08",
    name: "Leather Messenger Bag",
    category: "Bags",
    gender: "Men",
    price: 1680,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Flap-front calfskin messenger with concealed magnetic buckles.",
    description: "Wide canvas webbed shoulder strap and back slip pocket. Fits tablets and daily documents.",
    rating: 4.8,
    reviewsCount: 17,
    sizes: ["One Size"],
    colors: ["Black", "Cognac Leather"],
    badge: null,
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-b-09",
    name: "Croc-Embossed Leather Cardholder",
    category: "Accessories",
    gender: "Unisex",
    price: 280,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Slim 5-slot card case in crocodile-stamped calfskin.",
    description: "Gold foil logo stamp at front with central slip pocket for folded cash bills.",
    rating: 4.9,
    reviewsCount: 88,
    sizes: ["One Size"],
    colors: ["Emerald Croc", "Noir Croc", "Burgundy Croc"],
    badge: "Best Seller",
    isFeatured: false,
    isBestSeller: true
  },

  // WATCHES & TIMEPIECES (42 - 46)
  {
    id: "mv-wth-01",
    name: "Automatic Chronograph 41mm",
    category: "Watches",
    gender: "Men",
    price: 6800,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Swiss-made automatic movement with sapphire crystal back and alligator strap.",
    description: "42-hour power reserve, sunray dial, column-wheel chronograph mechanism, and 50m water resistance.",
    rating: 5.0,
    reviewsCount: 18,
    sizes: ["41mm"],
    colors: ["Silver/Black Leather", "Blue/Silver"],
    badge: "Masterpiece",
    isFeatured: true,
    isBestSeller: true
  },
  {
    id: "mv-wth-02",
    name: "Diamond Bezel Quartz Watch 32mm",
    category: "Watches",
    gender: "Women",
    price: 5400,
    salePrice: 4860,
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Mother-of-pearl dial framed by 36 brilliant-cut diamonds.",
    description: "Stainless steel case paired with an 18k rose gold-plated link bracelet and scratch-resistant sapphire glass.",
    rating: 4.9,
    reviewsCount: 22,
    sizes: ["32mm"],
    colors: ["Rose Gold / Pearl"],
    badge: "Sale",
    isFeatured: true,
    isBestSeller: false
  },
  {
    id: "mv-wth-03",
    name: "Ultra-Thin Dress Watch 38mm",
    category: "Watches",
    gender: "Unisex",
    price: 4200,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Manual wind mechanical movement measuring just 6.2mm case thickness.",
    description: "Minimalist enamel dial with leaf hands and hand-stitched Horween calfskin strap.",
    rating: 4.8,
    reviewsCount: 14,
    sizes: ["38mm"],
    colors: ["White/Black", "Champagne/Brown"],
    badge: null,
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-wth-04",
    name: "Diver Automatic 43mm",
    category: "Watches",
    gender: "Men",
    price: 4900,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
    shortDescription: "300m water-resistant diving watch with ceramic unidirectional bezel.",
    description: "Luminescent Super-LumiNova hands and hour markers. Solid 316L steel bracelet with diving extension buckle.",
    rating: 4.9,
    reviewsCount: 29,
    sizes: ["43mm"],
    colors: ["Matte Black", "Ocean Blue"],
    badge: null,
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-wth-05",
    name: "Rectangular Deco Gold Watch",
    category: "Watches",
    gender: "Women",
    price: 3800,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Art Deco-inspired rectangular case in 18k yellow gold vermeil.",
    description: "Roman numeral index markers, cabochon crown, and supple black lizard-grain leather strap.",
    rating: 4.7,
    reviewsCount: 11,
    sizes: ["26mm x 34mm"],
    colors: ["Gold/Black"],
    badge: "New Arrival",
    isFeatured: false,
    isBestSeller: false
  },

  // FINE ACCESSORIES & JEWELRY (47 - 50)
  {
    id: "mv-a-01",
    name: "Acetate Cat-Eye Sunglasses",
    category: "Accessories",
    gender: "Women",
    price: 450,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Hand-polished Japanese acetate sunglasses with 100% UV protection Carl Zeiss lenses.",
    description: "Beveled outer frame, 7-barrel hinges, and signature gold metal wire core inside the temples.",
    rating: 4.8,
    reviewsCount: 40,
    sizes: ["Standard"],
    colors: ["Tortoiseshell", "Solid Black"],
    badge: "Essential",
    isFeatured: true,
    isBestSeller: true
  },
  {
    id: "mv-a-02",
    name: "Monogram Silk Twill Scarf 90cm",
    category: "Accessories",
    gender: "Women",
    price: 490,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1584273143981-41c073dfe8f8?auto=format&fit=crop&w=800&q=80",
    shortDescription: "Pure silk twill scarf with hand-rolled edges screen printed in Lyon.",
    description: "Features custom Maison Vernis archival motif. Can be styled around the neck, hair, or bag handles.",
    rating: 4.9,
    reviewsCount: 33,
    sizes: ["90cm x 90cm"],
    colors: ["Ivory/Navy", "Terracotta/Gold"],
    badge: null,
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-a-03",
    name: "Reversible Leather Belt with Buckle",
    category: "Accessories",
    gender: "Men",
    price: 520,
    salePrice: 416,
    image: "https://cdn02.pinkoi.com/product/f3S2emQa/8/640x530.jpg",
    secondaryImage: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80",
    shortDescription: "35mm reversible belt in smooth black and textured tan calfskin.",
    description: "Rotating brushed palladium buckle featuring subtle laser-etched brand engraving.",
    rating: 4.8,
    reviewsCount: 26,
    sizes: ["85cm", "90cm", "95cm", "100cm"],
    colors: ["Black/Tan"],
    badge: "Sale",
    isFeatured: false,
    isBestSeller: false
  },
  {
    id: "mv-a-04",
    name: "Cashmere & Silk Fringed Stole",
    category: "Accessories",
    gender: "Unisex",
    price: 640,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=800&q=80",
    secondaryImage: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=800&q=80",
    shortDescription: "70% cashmere and 30% silk lightweight wrap scarf.",
    description: "Elegantly finished with subtle eyelash fringe borders. Soft, voluminous, and lightweight across seasons.",
    rating: 4.9,
    reviewsCount: 19,
    sizes: ["70cm x 200cm"],
    colors: ["Charcoal", "Camel", "Cream"],
    badge: "New Arrival",
    isFeatured: false,
    isBestSeller: false
  },
    {
    id: "mv-a-05",
    name: "Italian Leather Card Holder",
    category: "Accessories",
    gender: "Unisex",
    price: 280,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1563832007239-40e7ba6b5dd3?auto=format&fit=crop&fm=jpg&q=80&w=800",
    secondaryImage: "https://images.unsplash.com/photo-1635417198137-75d31b8045e2?auto=format&fit=crop&fm=jpg&q=80&w=800",
    shortDescription: "Hand-finished Italian leather card holder with a refined minimalist profile.",
    description: "Crafted from premium leather with clean edges and a compact silhouette designed for effortless everyday carry.",
    rating: 4.8,
    reviewsCount: 24,
    sizes: ["One Size"],
    colors: ["Black", "Cognac", "Dark Brown"],
    badge: "New Arrival",
    isFeatured: true,
    isBestSeller: false
  },

  {
    id: "mv-a-06",
    name: "Silk Signature Hair Scarf",
    category: "Accessories",
    gender: "Women",
    price: 220,
    salePrice: null,
    image: "https://images.unsplash.com/photo-1635417198137-75d31b8045e2?auto=format&fit=crop&fm=jpg&q=80&w=800",
    secondaryImage: "https://images.unsplash.com/photo-1563832007239-40e7ba6b5dd3?auto=format&fit=crop&fm=jpg&q=80&w=800",
    shortDescription: "Luxurious silk hair scarf finished with an elegant signature-inspired print.",
    description: "Lightweight pure-silk styling accessory designed to add a sophisticated finishing touch to everyday and evening looks.",
    rating: 4.9,
    reviewsCount: 17,
    sizes: ["65cm x 65cm"],
    colors: ["Ivory", "Black", "Burgundy"],
    badge: "Limited Edition",
    isFeatured: false,
    isBestSeller: true
  }
];

window.PRODUCTS = PRODUCTS;
// Helper Utilities
const Formatters = {
  currency: (amount) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      maximumFractionDigits: 0
    }).format(amount);
  }
};

console.log("conecction is safe");